### ISSUE TITLE
符号优化

### ISSUE THREAD

**Issue by gujunhk** [Openvingen/rime-zhengma#1]
当前符号希望能够优化
1. 能够继续使用/jt来输入箭头，以及类似的原先符号不要被覆盖。
2. 希望能够继续在中文模式下，正常能直接输入“、……”等标点符号，而不是Rime默认的出现候选框。

**Comment by Openvingen** [comment]
#### 1.  关于图形符号编码,a. mac、linux、win平台字体显示有差异,很多符号在不同平台不能正确显示(显示为方块或空白).  b.图形符号会带来大量重码,所以我把它们移除了.

#### 2.  要让中文常用标点直接上屏的配置在default.yaml, 你可以试试按自己喜好修改.
所有文件都是文本文件, 可根据个人喜受任意调校. 
我修改版已上传.
#### 例子
```  defalut.yaml
punctuator:
  full_shape:                              #全角符号 
    "!": {commit: "！"}               #侯选词上屏, 并且符号“!”上屏
    "\"": {pair: ["“", "”"]}            #成对轮流上屏
    "#": "#"                                 #直接上直接
    "$": ["￥", "$", "€", "£", "¥", "¢", "¤"]    #候选上屏
    .
    . 
  half_shape:                            #半角符号 
    "!": {commit: "!"}   
    .
    .
```
